# Generated by Django 4.2.3 on 2023-09-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=300)),
                ('pdf', models.ImageField(upload_to='pdf/')),
            ],
        ),
    ]
