# Generated by Django 4.2.3 on 2023-09-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='pdf',
            field=models.FileField(upload_to='pdf/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='summary',
            field=models.CharField(max_length=350),
        ),
    ]
