# Generated by Django 4.2.3 on 2023-09-24 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_job_pdf_alter_job_summary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
